document.writeln("<!-- sidebar left-->");
document.writeln("            <div class=\'page-sidebar \' id=\'main-menu\'>");
document.writeln("                <div class=\'page-sidebar-wrapper scroller scrollbar-dynamic\' id=\'main-menu-wrapper\'>");
document.writeln("                    <!-- 用户头像信息 -->");
document.writeln("                    <div class=\'user-info-wrapper sm\'>");
document.writeln("                        <!-- 头像 -->");
document.writeln("                        <a href=\'Profile.html\' class=\'profile-wrapper sm\'>");
document.writeln("                            <img src=\'assets/img/profiles/avatar.jpg\' alt=\'\' data-src=\'assets/img/profiles/avatar.jpg\' data-src-retina=\'assets/img/profiles/avatar2x.jpg\' width=\'69\' height=\'69\' />");
document.writeln("                        </a>");
document.writeln("                        <!-- 姓名、登录状态 -->");
document.writeln("                        <div class=\'user-info sm\'>");
document.writeln("                            <div class=\'username\'><span class=\'semi-bold\'>Welcome</span></div>");
document.writeln("                            <div class=\'username\'>John <span class=\'semi-bold\'>Smith</span></div>");
document.writeln("                            <div class=\'status\'>Status");
document.writeln("                                <div class=\'status-icon green\'></div> online    ");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
// document.writeln("                    <!-- BROWSE    -->");
// document.writeln("                    <p class=\'menu-title sm\'>BROWSE ");
// document.writeln("                        <span class=\'pull-right\'>");
// document.writeln("                            <a href=\'javascript:;\'>");
// document.writeln("                                <i class=\'fa fa-refresh\'></i>");
// document.writeln("                            </a>");
// document.writeln("                        </span>");
// document.writeln("                    </p>");
document.writeln("                    <!-- 链接列表 -->");
document.writeln("                    <ul>    ");
document.writeln("                        <!-- index -->");
document.writeln("                        <li class=\'start \'> ");
document.writeln("                            <a href=\'index.html\'>");
document.writeln("                                <i class=\'fa fa-home\'></i> ");
document.writeln("                                <span class=\'title\'>Index</span> ");
document.writeln("                                <span class=\'badge badge-important pull-right\'>5</span>");
document.writeln("                            </a>");
document.writeln("                        </li>");	
document.writeln("                        <!-- Tra Management -->");
document.writeln("                        <li>");
document.writeln("                            <a href=\'TradingStatistic.html\'> ");
document.writeln("                                <i class=\'fa fa-legal\'></i>");
document.writeln("                                <span class=\'title\'> Tra Management</span> ");
document.writeln("                                <span class=\' fa fa-angle-right pull-right m-t-5\'></span> ");
document.writeln("                            </a>");
document.writeln("                            <ul class=\'sub-menu\'>");
document.writeln("                                <li> ");
document.writeln("                                    <a href=\'TradingStatistic.html\'><i class=\'fa fa-bar-chart\'></i> Trading Statistics </a> ");
document.writeln("                                </li>");
document.writeln("                                <li> ");
document.writeln("                                    <a href=\'Tools.html\'><i class=\'fa fa-suitcase\'></i> Tools</a> ");
document.writeln("                                </li>");
document.writeln("                                <li> ");
document.writeln("                                    <a href=\'Trading_History.html\'><i class=\'fa fa-suitcase\'></i> Trading history</a> ");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                        <!-- Progress -->");
document.writeln("                        <li>");
document.writeln("                            <a href=\'Personal_management.html\'> ");
document.writeln("                                <i class=\'fa fa-user\'></i> ");
document.writeln("                                <span class=\'title\'> Personal Management</span> ");
document.writeln("                            </span>");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                        <!-- tv -->");
document.writeln("                        <li>");
document.writeln("                            <a href=\'Tv.html\'> ");
document.writeln("                                <i class=\'fa fa-tv\'></i> ");
document.writeln("                                <span class=\'title\'>TV</span> ");
document.writeln("                            </span>");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                        <!-- order -->");
document.writeln("                        <li>");
document.writeln("                            <a href=\'Order.html\'> ");
document.writeln("                                <i class=\'fa fa-file-text\'></i> ");
document.writeln("                                <span class=\'title\'>Order</span> ");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                        <!-- help -->");
document.writeln("                        <li>");
document.writeln("                            <a href=\'Help.html\'> ");
document.writeln("                                <i class=\'fa fa-question-circle\'></i> ");
document.writeln("                                <span class=\'title\'>Help</span> ");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                    <div class=\'side-bar-widgets\'>");
document.writeln("                        <p class=\'menu-title sm\'>Themes ");
document.writeln("                            <span class=\'pull-right\'>");
document.writeln("                                <a href=\'#\' class=\'create-folder\'> ");
document.writeln("                                    <i class=\'fa fa-plus\'></i>");
document.writeln("                                </a>");
document.writeln("                            </span>");
document.writeln("                        </p>");
document.writeln("                        <ul class=\'folders\'>");
document.writeln("                          <li>");
document.writeln("                            <a href=\'#\'>");
document.writeln("                                <i class=\'fa fa-circle-o\'></i>  white");
document.writeln("                            </a>");
document.writeln("                          </li>");
document.writeln("                          <li>");
document.writeln("                            <a href=\'#\'>");
document.writeln("                                <i class=\'fa fa-circle-o text-block\'></i> block ");
document.writeln("                            </a>");
document.writeln("                          </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <a href=\'#\' class=\'scrollup\'>Scroll</a>");
document.writeln("            <!-- exit -->");
document.writeln("            <div class=\'footer-widget\'>");
document.writeln("                <div class=\'progress transparent progress-small no-radius no-margin\'>");
document.writeln("                  <div class=\'progress-bar progress-bar-success animate-progress-bar\' data-percentage=\'79%\' style=\'width: 79%;\'></div>");
document.writeln("                </div>");
document.writeln("                <div class=\'pull-right\'>");
document.writeln("                    <div class=\'details-status\'> ");
document.writeln("                        <span class=\'animate-number\' data-value=\'86\' data-animation-duration=\'560\'>86</span>% ");
document.writeln("                    </div>");
document.writeln("                    <a href=\'lockscreen.html\'>");
document.writeln("                        <i class=\'fa fa-power-off\'></i>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("             <!-- sidebar right notice-->");
document.writeln("            <div class=\'notice-box\'>");
document.writeln("                <div  class=\'inner-content scroller scrollbar-dynamic\'>");
document.writeln("                    <div class=\'notice-header\'>");
document.writeln("                        <input type=\'text\' placeholder=\'search\' >");
document.writeln("                        <a href=\'#\' class=\'pull-right\'>");
document.writeln("                            <div class=\'iconset top-settings-dark\'></div>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                    <!-- notice -->");
document.writeln("                    <div class=\'notice fadeIn\'>");
document.writeln("                        <!-- date -->");
document.writeln("                        <div class=\'notice-date\'>");
document.writeln("                            <div class=\'pull-left day-num text-c2\'>08.APR</div><span class=\'day\'></span> Monday");
document.writeln("                            <i class=\'fa fa-plus pull-right\'></i>");
document.writeln("                        </div>");
document.writeln("                        <!-- 中间线 -->");
document.writeln("                        <div class=\'notice-timeline\'></div>");
document.writeln("                        <!-- notice content -->");
document.writeln("                        <div class=\'notice-content\'>");
document.writeln("                            <div class=\'notice-card\'>");
document.writeln("                                <!-- title -->");
document.writeln("                                <div class=\'card-title\'>");
document.writeln("                                    <div class=\'pull-left\'>12:00</div>");
document.writeln("                                    <div class=\'status-icon green pull-right\'></div>");
document.writeln("                                </div>");
document.writeln("                                <!-- body -->");
document.writeln("                                <div class=\'card-body\'>");
document.writeln("                                    <h5>The problem you submitted a new reply</h5>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'notice-card\'>");
document.writeln("                                <!-- title -->");
document.writeln("                                <div class=\'card-title\'>");
document.writeln("                                    <div class=\'pull-left\'>11:00</div>");
document.writeln("                                    <div class=\'status-icon grey pull-right\'></div>");
document.writeln("                                </div>");
document.writeln("                                <!-- body -->");
document.writeln("                                <div class=\'card-body\'>");
document.writeln("                                    <h5>The problem you submitted a <a href=\'\' class=\'text-primary\'>new reply &gt;&gt;</a></h5>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'notice-card\'>");
document.writeln("                                <!-- title -->");
document.writeln("                                <div class=\'card-title\'>");
document.writeln("                                    <div class=\'pull-left\'>10:00</div>");
document.writeln("                                    <div class=\'status-icon grey pull-right\'></div>");
document.writeln("                                </div>");
document.writeln("                                <!-- body -->");
document.writeln("                                <div class=\'card-body\'>");
document.writeln("                                    <h5>The problem you submitted a  <a href=\'\' class=\'text-success\'>new reply &gt;&gt;</a> </h5>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'notice fadeIn\'>");
document.writeln("                        <!-- date -->");
document.writeln("                        <div class=\'notice-date\'>");
document.writeln("                            <div class=\'pull-left day-num text-c2\'>08.APR</div><span class=\'day\'></span> Monday");
document.writeln("                            <i class=\'fa fa-plus pull-right\'></i>");
document.writeln("                        </div>");
document.writeln("                        <!-- 中间线 -->");
document.writeln("                        <div class=\'notice-timeline\'></div>");
document.writeln("                        <!-- notice content -->");
document.writeln("                        <div class=\'notice-content\'>");
document.writeln("                            <div class=\'notice-card\'>");
document.writeln("                                <!-- title -->");
document.writeln("                                <div class=\'card-title\'>");
document.writeln("                                    <div class=\'pull-left\'>12:00</div>");
document.writeln("                                    <div class=\'status-icon green pull-right\'></div>");
document.writeln("                                </div>");
document.writeln("                                <!-- body -->");
document.writeln("                                <div class=\'card-body\'>");
document.writeln("                                    <h5>The problem you submitted a new reply</h5>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'notice-card\'>");
document.writeln("                                <!-- title -->");
document.writeln("                                <div class=\'card-title\'>");
document.writeln("                                    <div class=\'pull-left\'>11:00</div>");
document.writeln("                                    <div class=\'status-icon grey pull-right\'></div>");
document.writeln("                                </div>");
document.writeln("                                <!-- body -->");
document.writeln("                                <div class=\'card-body\'>");
document.writeln("                                    <h5>The problem you submitted a <a href=\'\' class=\'text-primary\'>new reply &gt;&gt;</a></h5>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'notice-card\'>");
document.writeln("                                <!-- title -->");
document.writeln("                                <div class=\'card-title\'>");
document.writeln("                                    <div class=\'pull-left\'>10:00</div>");
document.writeln("                                    <div class=\'status-icon grey pull-right\'></div>");
document.writeln("                                </div>");
document.writeln("                                <!-- body -->");
document.writeln("                                <div class=\'card-body\'>");
document.writeln("                                    <h5>The problem you submitted a  <a href=\'\' class=\'text-success\'>new reply &gt;&gt;</a> </h5>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>  ");