document.writeln("<div class=\'header navbar navbar-inverse \'>");
document.writeln("		    <div class=\'header navbar navbar-inverse \'>");
document.writeln("		        <div class=\'navbar-inner\'>");
document.writeln("		            <!-- sidebar top -->");
document.writeln("		            <div class=\'header-seperation\'>");
document.writeln("		                <!-- 响应式隐藏菜单 左侧-->");
document.writeln("		                <ul class=\'nav pull-left notifcation-center visible-xs visible-sm\'>");
document.writeln("		                    <li class=\'dropdown\'>");
document.writeln("		                        <a href=\'#main-menu\' data-webarch=\'toggle-left-side\'>");
document.writeln("		                            <i class=\'fa fa-bars\'></i>");
document.writeln("		                        </a>");
document.writeln("		                    </li>");
document.writeln("		                </ul>");
document.writeln("		                <!-- LOGO -->");
document.writeln("		                <a href=\'index.html\'>");
document.writeln("		                    <img src=\'assets/img/alpha_logo.png\' class=\'logo\' alt=\'\' data-src=\'assets/img/alpha_logo.png\' data-src-retina=\'../assets/img/alpha_logo.png\'  />");
document.writeln("		                </a>");
document.writeln("		            </div>");
document.writeln("		            <!-- navbar-->");
document.writeln("		            <div class=\'header-quick-nav\'>");
document.writeln("		                <!-- navbar left-->");
document.writeln("		                <div class=\'pull-left\'>");
document.writeln("		                    <ul class=\'nav quick-section\'>");
document.writeln("		                        <li class=\'quicklinks\'>");
document.writeln("		                            <a href=\'#\' class=\'\' id=\'layout-condensed-toggle\'>");
document.writeln("		                                <i class=\'fa fa-reorder\'></i>");
document.writeln("		                            </a>");
document.writeln("		                        </li>");
document.writeln("		                    </ul>");
document.writeln("		                    <ul class=\'nav quick-section\'>");
document.writeln("		                    </ul>");
document.writeln("		                </div>");
document.writeln("		                <!-- navbar right -->");
document.writeln("		            </div>");
document.writeln("		        </div>");
document.writeln("		    </div>");
document.writeln("		</div>");