document.writeln("<div class=\'header navbar navbar-inverse \'>");
document.writeln("		    <div class=\'header navbar navbar-inverse \'>");
document.writeln("		        <div class=\'navbar-inner\'>");
document.writeln("		            <!-- sidebar top -->");
document.writeln("		            <div class=\'header-seperation\'>");
document.writeln("		                <!-- 响应式隐藏菜单 左侧-->");
document.writeln("		                <ul class=\'nav pull-left notifcation-center visible-xs visible-sm\'>");
document.writeln("		                    <li class=\'dropdown\'>");
document.writeln("		                        <a href=\'#main-menu\' data-webarch=\'toggle-left-side\'>");
document.writeln("		                            <i class=\'fa fa-bars\'></i>");
document.writeln("		                        </a>");
document.writeln("		                    </li>");
document.writeln("		                </ul>");
document.writeln("		                <!-- LOGO -->");
document.writeln("		                <a href=\'index.html\'>");
document.writeln("		                    <img src=\'assets/img/alpha_logo.png\' class=\'logo\' alt=\'\' data-src=\'assets/img/alpha_logo.png\' data-src-retina=\'../assets/img/alpha_logo.png\'  />");
document.writeln("		                </a>");
// document.writeln("		                <!-- 主页和邮箱 -->");
// document.writeln("		                <ul class=\'nav pull-right notifcation-center\'>");
// document.writeln("		                    <!-- 主页 -->");
// document.writeln("		                    <li class=\'dropdown hidden-xs hidden-sm\'>");
// document.writeln("		                        <a href=\'index.html\' class=\'dropdown-toggle active\' data-toggle=\'\'>");
// document.writeln("		                            <i class=\'fa fa-home\'></i>");
// document.writeln("		                        </a>");
// document.writeln("		                    </li>");
// document.writeln("		                    <!-- 邮箱 -->");
// document.writeln("		                    <li class=\'dropdown hidden-xs hidden-sm\'>");
// document.writeln("		                        <a href=\'\' class=\'dropdown-toggle\'>");
// document.writeln("		                            <i class=\'fa fa-envelope-o\'></i><span class=\'badge badge-important\'>2</span>");
// document.writeln("		                        </a>");
// document.writeln("		                    </li>");
// document.writeln("		                    <li class=\'dropdown visible-xs visible-sm\'>");
// document.writeln("		                        <a href=\'\' data-webarch=\'toggle-right-side\'>");
// document.writeln("		                            <i class=\'fa fa-search\'></i>");
// document.writeln("		                        </a>");
// document.writeln("		                    </li>");
// document.writeln("		                </ul>");
document.writeln("		            </div>");
document.writeln("		            <!-- navbar-->");
document.writeln("		            <div class=\'header-quick-nav\'>");
document.writeln("		                <!-- navbar left-->");
document.writeln("		                <div class=\'pull-left\'>");
document.writeln("		                    <ul class=\'nav quick-section\'>");
document.writeln("		                        <li class=\'quicklinks\'>");
document.writeln("		                            <a href=\'#\' class=\'\' id=\'layout-condensed-toggle\'>");
document.writeln("		                                <i class=\'fa fa-reorder\'></i>");
document.writeln("		                            </a>");
document.writeln("		                        </li>");
document.writeln("		                    </ul>");
document.writeln("		                    <ul class=\'nav quick-section\'>");
document.writeln("		                        <li class=\'quicklinks  m-r-10\'>");
document.writeln("		                            <a href=\'#\' class=\'\'>");
document.writeln("		                                <i class=\'fa fa-refresh\'></i>");
document.writeln("		                            </a>");
document.writeln("		                        </li>");
document.writeln("		                        <li class=\'m-r-10 input-prepend inside search-form no-boarder\' >");
document.writeln("		                            <span class=\'add-on\' > <i class=\'fa fa-search\'></i></span>");
document.writeln("		                            <input name=\'\' type=\'text\' class=\'no-boarder\' placeholder=\'Search Dashboard\' style=\'width:250px;\'>");
document.writeln("		                        </li>");
document.writeln("		                    </ul>");
document.writeln("		                </div>");
document.writeln("		                <!-- navbar right -->");
document.writeln("		                <div class=\'pull-right\'>");
document.writeln("		                    <ul class=\'nav quick-section \'>");
document.writeln("		                        <!-- 邮箱 -->");
document.writeln("		                        <li class=\'dropdown hidden-xs hidden-sm\'>");
document.writeln("		                            <a href=\'\' class=\'dropdown-toggle\' data-webarch=\'toggle-right-side\'>");
document.writeln("		                                <i class=\'fa fa-envelope-o\'></i><span class=\'badge badge-important\'>2</span>");
document.writeln("		                            </a>");
document.writeln("		                             <div class=\'simple-chat-popup chat-menu-toggle hide\'>");
document.writeln("		                                <div class=\'simple-chat-popup-arrow\'></div>");
document.writeln("		                                <div class=\'simple-chat-popup-inner\'>");
document.writeln("		                                    <div style=\'width:100px\'>");
document.writeln("		                                        <div class=\'semi-bold\'>David Nester</div>");
document.writeln("		                                        <div class=\'message\'>Hey you there </div>");
document.writeln("		                                    </div>");
document.writeln("		                                </div>");
document.writeln("		                            </div>");
document.writeln("		                        </li>");
document.writeln("		                    </ul>");
document.writeln("		                </div>");
document.writeln("		            </div>");
document.writeln("		        </div>");
document.writeln("		    </div>");
document.writeln("		</div>");